version: '3.3'
services:
    sqlserver:
        environment:
            - ACCEPT_EULA=Y
            - 'MSSQL_SA_PASSWORD=myStrongPassword12#'
        ports:
            - '1433:1433'
        volumes:
            - 'sqldata:/var/opt/mssql/sqlserver'
        container_name: sqlserver
        deploy:
          resources:
            reservations:
              cpus: '2'
              memory: 2GB
        image: mcr.microsoft.com/mssql/server
    webapp:    
        ports:
            - '80:80'
        container_name: webapp
        restart: on-failure
        image: ivocontactslibrary.azurecr.io/contacts
        domainname: ivailohasovcontacts
        build:
            dockerfile: ./Dockerfile
volumes:
  sqldata:
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: ivohascontactssa
      