version: '3.8'
services:
    sqldata:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server
        ports:
            - "1433:1433"
        deploy:
          resources:
            reservations:
              cpus: '2'
              memory: 2GB
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=yourStrongPassword12#
        volumes:
            - sqldata:/var/opt/mssql/server
    webapp: 
      ports:
        - '80:80'
      container_name: webapp
      restart: on-failure
      image: ivailohasovbazarscr.azurecr.io/bazar
      domainname: ivailohasovbazar
volumes:
  sqldata:
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: ivailohasovbazarsa
      